---
title: "2_EnrichmentReport"
author: "Daniel Dimitrov"
date: "9/15/2022"
output: html_document
---


## Load Required Libs
```{r setup, include=FALSE}
require(tidyverse)
require(reticulate)
require(Seurat)
require(magrittr)
```


### Load Relevant Libraries

```{python}
import scanpy as sc
import decoupler as dc

# Only needed for processing and plotting
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
```


## Load the adata object, as prepared by Part1
```{python}
adata = sc.read_h5ad("data/adata.h5ad")
```


### Convert it to Seurat
```{r}
#' Function to Convert adata to Seurat object
#' @param adata anndata object as obtain from the function above
#' @returns a Seurat object
adata_to_seurat <- function(adata){
    # Counts
    counts <- as(t(as.matrix(py$adata$layers['counts'])), "CsparseMatrix")
    colnames(counts) <- py$adata$obs_names$to_list()
    rownames(counts) <- py$adata$var_names$to_list()
    
    # Data
    logcounts <- as(t(as.matrix(py$adata$layers['logcounts'])), "CsparseMatrix")
    colnames(logcounts) <- py$adata$obs_names$to_list()
    rownames(logcounts) <- py$adata$var_names$to_list()
    
    # Create the Seurat object
    seurat_object <- CreateSeuratObject(counts)
    # Set the expression assay
    seurat_object <- SetAssayData(seurat_object, "counts", counts)
    # log-normalize
    seurat_object <- NormalizeData(seurat_object)
    
    # Add observation metadata
    seurat_object <- AddMetaData(seurat_object, py$adata$obs)
    return(seurat_object)
}
```

```{r}
# Get Seurat Object
sobj <- adata_to_seurat(py$adata)
Idents(sobj) <- sobj@meta.data$cell_type

# Save Seurat Object
saveRDS(sobj, "data/sobj.RDS")
```
